##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: "Franchises"
  devtools:
    add-properties: false
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:franchises_api_db}"
    username: "${DB_USER:postgres}"
    password: "${DB_PASSWORD:password123}"
  flyway:
    enabled: true
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:franchises_api_db}"
    user: "${DB_USER:postgres}"
    password: "${DB_PASSWORD:password123}"
  h2:
    console:
      enabled: false
      path: "/h2"
  profiles:
    include: null
adapters:
  r2dbc:
    host: "${DB_HOST:localhost}"
    port: "${DB_PORT:5432}"
    database: "${DB_NAME:franchises_api_db}"
    schema: "public"
    username: "${DB_USER:postgres}"
    password: "${DB_PASSWORD:password123}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
